### ISSUE TITLE
Ignore Protected/Reference Questions

### ISSUE THREAD

**Issue by ghost** [Room-11/CVBacklog#6]
Right now the pinned cv-pls message in chat is marking the reference questions as cv-pls so they show up in the backlog. One of them is the [operators](http://stackoverflow.com/questions/3737139/reference-what-does-this-symbol-mean-in-php) reference which is marked as protected. 

Can we have a whitelist in effect by having the backlog ignore protected questions? This way we can easily whitelist a question by marking it as protected. If the API does not allow fetching the protected status of the question, then an alternative would be to drop any question titles which begin with the string _'Reference '_ from being added to the backlog.

Either the `preg_match_all()` regex can be modified to not match URLs that contain titles beginning with 'reference-' or drop it later on in the process in case title has been changed and canonical URL's title no longer matches. I'd make a commit, but I would just mess up all the OOP =oP

**Comment by gooh** [comment]
I've already implemented a blacklist a while ago. The backlog will ignore all question IDs in that list. I'll add the question IDs in the next days.

See https://github.com/gooh/CVBacklog/commit/6c718d5f6e1f4476ff3db3715f0c826efdd104bb for reference.
